### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by NewbieAngular** [lgdd/log4javascript-demo#1]
I am using the ajax appender as your example. '/log/javascript' is a handler method in the controller. As this would be used across different apps, I had this method defined abstract. 
......
@RequestMapping(value = "/log/javascript",  method = RequestMethod.POST, produces = "application/json", headers="Accept=application/json")
    abstract ObjectNode logJavascript(@RequestBody LogMessage[] messages) {
......
and extended in my server controller.

public class MyController extends AbstractLogController

........

For angular 1 apps, I had no issue with this implementation.I didn't have to override the super class method.  For angular  4 apps, I get a 502 error. However, if I override the logJavascript method in my controller,  I don't see this issue. Any suggestions?

**Comment by lgdd** [comment]
Hi,

Even though you could fix your issue by overriding the `logJavascript` method, it sounds like it could be related to some configuration on the Angular side.
Could you share any relevant code / config file from your Angular client that could give me a better understanding?
Also, could you share more Java code to see more clearly how you use your `AbstractLogController` and its methods, and how it exposes to `/log/javascript`?

_P.S.: Sorry for the late answer._
